trigger:
- main

pool:
  name: 'Default'

stages:
  - stage:
    jobs:
     - job:
       steps:
         - task: Maven@4
           inputs:
             mavenPOMFile: 'pom.xml'
             goals: 'package'
             publishJUnitResults: true
             testResultsFiles: '**/surefire-reports/TEST-*.xml'
         - task: CopyFiles@2 
           inputs:
             Contents: '**'
             TargetFolder: $(Build.ArtifactStagingDirectory)
         - publish: '$(Build.ArtifactStagingDirectory)/scripts'
           displayName: 'Publish script'
           artifact: drop    

